# Generated by Django 4.2.7 on 2023-11-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookbook',
            name='copies_available',
            field=models.IntegerField(default=100),
        ),
    ]
