# Generated by Django 4.2.7 on 2023-11-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_ebookbook_copies_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
