# Generated by Django 4.2.7 on 2023-11-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_remove_transaction_user_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='return_date',
            new_name='returned_date',
        ),
    ]
