# Generated by Django 4.2.7 on 2023-11-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_remove_transaction_book_transaction_audiobook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
