# Generated by Django 4.2.7 on 2023-11-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_alter_transaction_returned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('ebook', 'Ebook'), ('audiobook', 'Audiobook'), ('paperback', 'Paperback')], max_length=10, null=True),
        ),
    ]
