# Generated by Django 4.2.7 on 2023-11-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_book_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
    ]
