# Generated by Django 4.2.7 on 2023-11-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_remove_book_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='audioBook',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ebook_book',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='hardcover_book',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paperbackBook',
        ),
    ]
