# Generated by Django 4.2.7 on 2023-11-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_remove_transaction_audiobook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('ebook', 'Ebook'), ('audiobook', 'Audiobook'), ('paperback', 'Paperback')], max_length=10, null=True),
        ),
    ]
